# Generated by Django 4.2.7 on 2024-01-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usertbl',
            fields=[
                ('userRegnoID', models.IntegerField(primary_key=True, serialize=False)),
                ('usertype', models.CharField(choices=[('USER', 'user'), ('STAFF', 'staff')], max_length=10)),
                ('username', models.TextField(max_length=255)),
                ('useremail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
