# Generated by Django 4.2.7 on 2024-01-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usertbl',
            fields=[
                ('userRegnoID', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=255)),
                ('useremail', models.EmailField(help_text='Enter your valid email address.', max_length=254, unique=True, verbose_name='Email Address')),
            ],
        ),
    ]
