# Generated by Django 4.2.7 on 2024-02-05 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderstbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Dryclean', 'Dryclean'), ('NormalWash', 'NormalWash')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('expected_delivery_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModule.usertbl')),
            ],
        ),
    ]
