# Generated by Django 4.2.7 on 2024-01-28 19:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertbl',
            name='useremail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Orderstbl',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('dept', models.CharField(choices=[('dept1', 'Department 1'), ('dept2', 'Department 2')], max_length=10)),
                ('service', models.CharField(choices=[('service1', 'Service 1'), ('service2', 'Service 2')], max_length=10)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)])),
                ('orderdate', models.DateField(auto_now_add=True)),
                ('expected_delivery', models.DateField()),
                ('userRegnoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModule.usertbl')),
            ],
        ),
    ]
