# Generated by Django 4.2.7 on 2024-02-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertbl',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
