# Generated by Django 4.2.7 on 2024-02-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_completed',
        ),
        migrations.AddField(
            model_name='orderstbl',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
