# Generated by Django 4.2.7 on 2024-02-05 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0004_remove_payment_payment_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstbl',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
