# Generated by Django 4.2.7 on 2024-02-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0007_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
    ]
