# Generated by Django 4.2.7 on 2024-02-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0007_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
        migrations.AddField(
            model_name='usertbl',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertbl',
            name='usertype',
            field=models.CharField(choices=[('USER', 'user'), ('STAFF', 'staff'), ('ADMIN', 'admin')], max_length=10),
        ),
    ]
